package com.pe.botica.util;

public enum RolePermission {
    READ_ALL_CATEGORIES,
    READ_CATEGORY_BY_ID,
    REGISTER_CATEGORY,
    DELETE_CATEGORY,


    READ_ALL_PRODUCTS,
    READ_ALL_PRODUCT_OPTIONS,
    READ_ALL_PRODUCTS_WITH_DETAILS,
    READ_ALL_MY_PRODUCTS,
    READ_PRODUCT_BY_ID,
    REGISTER_PRODUCT,
    DELETE_PRODUCT,


    READ_ALL_SERVICES,
    READ_ALL_SERVICE_OPTIONS,
    READ_ALL_SERVICES_WITH_DETAILS,
    READ_ALL_MY_SERVICES,
    READ_SERVICE_BY_ID,
    REGISTER_SERVICE,
    DELETE_SERVICE,


    READ_ALL_ROLES,
    READ_ROLE_BY_ID,
    REGISTER_ROLE,
    DELETE_ROLE,


    READ_ALL_PURCHASES,
    READ_PURCHASE_BY_ID,
    REGISTER_PURCHASE,
    DELETE_PURCHASE,


    READ_ALL_PURCHASE_DETAILS,
    READ_PURCHASE_DETAIL_BY_ID,
    REGISTER_PURCHASE_DETAIL,
    DELETE_PURCHASE_DETAIL,


    READ_ALL_USERS,
    READ_USER_BY_ID,
    REGISTER_USER,
    DELETE_USER,
    READ_MY_PROFILE,


    READ_ALL_DRUGSTORE_PRODUCTS,
    READ_DRUGSTORE_PRODUCT_BY_ID,
    REGISTER_DRUGSTORE_PRODUCT,
    UPDATE_DRUGSTORE_PRODUCT,
    DELETE_DRUGSTORE_PRODUCT,


    READ_ALL_DRUGSTORE_SERVICES,
    READ_DRUGSTORE_SERVICE_BY_ID,
    REGISTER_DRUGSTORE_SERVICE,
    UPDATE_DRUGSTORE_SERVICE,
    DELETE_DRUGSTORE_SERVICE;
}
